각 성분에 적용되는 함수  
numpy에서는 array에 적용할 수 있는 다양한 함수를 제공한다.  

In [7]:
import numpy as np

In [8]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [11]:
x = np.random.randn(8)
y = np.random.randn(8)

In [12]:
x

array([ 0.24749152,  1.10232335,  0.20623389,  0.27753415, -2.27664406,
        0.22823152, -0.63675887,  1.40547766])

In [13]:
y

array([ 0.91601582,  1.83768726,  0.6823677 ,  0.83278657, -0.22087786,
       -0.02814861,  0.60017772,  0.40947582])

In [14]:
np.maximum(x,y)

array([ 0.91601582,  1.83768726,  0.6823677 ,  0.83278657, -0.22087786,
        0.22823152,  0.60017772,  1.40547766])

numpy에서 두 개의 array의 각 성분에 적용되는 함수  
add, subtract, multiply, divide, maximum, minimum  

numpy의 통계함수  
전체 성분의 값: sum, mean, std, var, min, max, argmin, argmax  
첫 번째 성분부터 각 성분까지 누적값을 계산: cumsum, cumprod  

In [15]:
arr = np.random.randn(5,4)
arr

array([[ 0.7900502 ,  0.08436601, -0.03020109, -0.64592323],
       [ 0.16192847,  1.50365918,  1.48829008,  1.15340634],
       [ 0.19900418,  1.59965013,  0.97136722, -0.15524874],
       [-0.58723452,  0.78061789, -1.07557497, -0.68906759],
       [ 0.17130699,  0.5689733 ,  1.19315033,  1.38655421]])

In [16]:
arr.sum()

8.869074393099968

In [17]:
arr.mean()

0.4434537196549984

In [18]:
# 행방향으로 열 값들에 대한 연산 수행  
arr.sum(axis=0)

array([0.73505532, 4.5372665 , 2.54703157, 1.04972099])

In [19]:
# 열방향으로 행 값들에 대한 연산 수행
arr.sum(axis=1)

array([ 0.19829188,  4.30728407,  2.61477279, -1.57125918,  3.31998483])

In [20]:
# 조건부 연산
arr > 0

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

In [21]:
(arr>0).sum() # True 값

14

정렬 함수 및 기타 함수

In [22]:
arr = np.random.randn(8)
arr

array([ 1.14223644,  0.27324705,  0.46821794, -0.4756932 ,  1.17683082,
       -0.30594527, -1.73972545,  0.09599093])

In [23]:
# 오름차순 정렬
np.sort(arr)

array([-1.73972545, -0.4756932 , -0.30594527,  0.09599093,  0.27324705,
        0.46821794,  1.14223644,  1.17683082])

In [24]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([ 1.17683082,  1.14223644,  0.46821794,  0.27324705,  0.09599093,
       -0.30594527, -0.4756932 , -1.73972545])

In [25]:
# 2차원 정렬
arr = np.random.randn(5,3)
arr

array([[-1.45554296, -0.58547044, -1.58876182],
       [ 0.97779146, -1.3570964 ,  0.03313199],
       [-0.62689779, -1.38076752,  0.13473516],
       [-0.1404608 , -2.09747187, -0.05716671],
       [ 0.82823547, -0.30185046,  0.13310149]])

In [26]:
# 행방향 열의 값을 오름차순 정렬
np.sort(arr, axis=0)

array([[-1.45554296, -2.09747187, -1.58876182],
       [-0.62689779, -1.38076752, -0.05716671],
       [-0.1404608 , -1.3570964 ,  0.03313199],
       [ 0.82823547, -0.58547044,  0.13310149],
       [ 0.97779146, -0.30185046,  0.13473516]])

In [27]:
# 열방향 행의 값을 오름차순 정렬
np.sort(arr, axis=1)

array([[-1.58876182, -1.45554296, -0.58547044],
       [-1.3570964 ,  0.03313199,  0.97779146],
       [-1.38076752, -0.62689779,  0.13473516],
       [-2.09747187, -0.1404608 , -0.05716671],
       [-0.30185046,  0.13310149,  0.82823547]])

 만약 길이가 아주 긴 large_arr array가 정의되어 있을 때, 해당 array 상에서 상위 5%에 위치하는 값은?

In [28]:
large_arr = np.random.randn(150)
large_arr

array([ 1.63040840e+00, -1.00522824e+00, -5.14718408e-01,  9.82816565e-01,
       -1.19346772e+00,  2.08980997e-01, -6.89372765e-01, -6.31123075e-01,
        5.97960635e-04,  6.90332342e-01,  2.06332842e+00, -4.72153827e-01,
        9.58129636e-01, -2.22674199e+00, -1.22342767e+00,  8.62174532e-01,
       -1.05962496e+00, -5.73572264e-01, -1.34028852e+00, -1.36833769e+00,
        1.20003150e+00, -1.21099233e+00, -7.60740902e-01, -3.03684887e-01,
       -2.61049108e+00, -1.48392822e-01, -1.56502600e+00, -2.32964959e+00,
        3.29268987e-01,  8.75958437e-01, -5.22048097e-01, -1.94472036e-01,
        3.33359661e-01, -5.94237224e-01,  2.09588002e-01,  3.49191127e-01,
        2.15319612e-01, -7.45473573e-01,  1.45569862e+00, -2.16114559e+00,
       -6.51869840e-01,  3.92127531e-01,  5.14563597e-01, -7.07581905e-01,
        7.46297830e-01,  1.04972633e+00, -2.36576551e-02,  1.09604372e+00,
       -4.94595147e-01,  5.89626541e-01, -4.43889506e-01,  2.07293259e-01,
        2.21328609e-01, -

In [29]:
np.sort(large_arr)[::-1]

array([ 2.32893717e+00,  2.27099959e+00,  2.06332842e+00,  1.90943344e+00,
        1.78168871e+00,  1.63040840e+00,  1.57916782e+00,  1.54306223e+00,
        1.45569862e+00,  1.41848956e+00,  1.39733416e+00,  1.29984828e+00,
        1.28556067e+00,  1.24389981e+00,  1.20003150e+00,  1.19958691e+00,
        1.12598662e+00,  1.09936913e+00,  1.09680525e+00,  1.09604372e+00,
        1.07287506e+00,  1.05248149e+00,  1.04972633e+00,  1.04058820e+00,
        9.82816565e-01,  9.58129636e-01,  9.35410876e-01,  8.75958437e-01,
        8.62174532e-01,  7.79527415e-01,  7.46297830e-01,  7.44487963e-01,
        7.35606547e-01,  7.26422828e-01,  6.90332342e-01,  6.70362328e-01,
        6.67739836e-01,  6.47701476e-01,  6.34559085e-01,  6.33996781e-01,
        5.93704883e-01,  5.89626541e-01,  5.89603389e-01,  5.86649611e-01,
        5.72424752e-01,  5.19650116e-01,  5.14563597e-01,  4.99803405e-01,
        4.77352305e-01,  4.59088934e-01,  4.51357661e-01,  4.07045979e-01,
        3.92127531e-01,  

In [30]:
int(0.05*len(large_arr))

7

In [31]:
np.sort(large_arr)[::-1][int(0.05*len(large_arr))]

1.5430622343666585

In [32]:
# 중복된 값 제거하기 - unique()
names = np.array(['ccc', 'hhh', 'ccc', 'bbb', 'jjj', 'jjj', 'ttt', 'ttt'])
int1 = np.array([3,3,3,4,4,1,1,2,5,5,6,8])

In [33]:
np.unique(names)

array(['bbb', 'ccc', 'hhh', 'jjj', 'ttt'], dtype='<U3')

In [34]:
np.unique(int1)

array([1, 2, 3, 4, 5, 6, 8])

In [37]:
np.sort(large_arr)[::-1][0:int(0.05*len(large_arr))]

array([2.32893717, 2.27099959, 2.06332842, 1.90943344, 1.78168871,
       1.6304084 , 1.57916782])

In [36]:
data = np.genfromtxt('./data/movielens/ratings.dat', delimiter = '::', dtype=np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [47]:
np.mean(data[:, 2])

3.581564453029317

In [51]:
data[:, 2].mean()

3.581564453029317

In [71]:
user_ids = np.unique(data[:,0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [72]:
user_ids.shape

(6040,)

In [73]:
# 빈 리스트 생성
mean_rating_by_user_list = []

for user_id in user_ids:
    data_for_user = data[data[:,0] == user_id, :] # 특정 user_id 값들의 array를 저장한 변수(unique값별로 지정)
    mean_rating_for_user = data_for_user[:, 2].mean() # rating의 평균
    mean_rating_by_user_list.append([user_id, mean_rating_for_user]) # 빈 리스트에 값 넣기

In [75]:
mean_rating_by_user_list[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]