In [1]:
import numpy as np

## 1차원 array

In [3]:
data = [6,7.5,8,0,1]

In [4]:
data

[6, 7.5, 8, 0, 1]

In [5]:
arr1 = np.array(data)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
arr1.shape

(5,)

In [7]:
arr = np.array([2,3,4])
arr

array([2, 3, 4])

## 2차원 array

In [8]:
data2 = [[1,2,3,4], [5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

## zeros(), ones(), arrange() 함수 기능

In [12]:
# 0으로 된 array 만들기
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##  데이터 타입
numpy에서 사용 가능한 데이터형(dtype) 정리  
  
**int8, int16, int32, int64** : 부호가 있는 [8, 16, 32, 64]비트 정수  
**unit8, unit16, unit32, unit64** : 부호가 없는 [8, 16, 32, 64]비트 정수  
**float16, float32, float64, float128** : [16, 32, 64, 128]비트 실수  
**complex64, complex128, complex256, complex512** : [64, 128, 256, 512]비트 복소수  

int 부호가 있는 정수  
unit 부호가 없는 정수  
float 실수  
complex 복소수  
bool 불리언 (True 또는 False)  
object python object 형  
string 문자열  
unicode 유니코드 문자열  

In [2]:
float_arr = arr.astype(np.float64)
float_arr

NameError: name 'arr' is not defined

In [18]:
float_arr.dtype

dtype('float64')

In [19]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
arr2 = np.array([[7,8,9], [10,11,12]], dtype=np.float64)

In [20]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [22]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [23]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [24]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

# array 인덱싱

In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [31]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
arr2[2, :]

array([ 9, 10, 11, 12])

In [35]:
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr2[:,3]

array([ 4,  8, 12, 16])

In [37]:
arr2[:,-1]

array([ 4,  8, 12, 16])

In [38]:
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

# 불리언 인덱싱

In [39]:
names = np.array(['ccc', 'hhh', 'bbb', 'ccc', 'bbb', 'hhh', 'ccc'])
data = np.random.randn(7,4)

In [40]:
names

array(['ccc', 'hhh', 'bbb', 'ccc', 'bbb', 'hhh', 'ccc'], dtype='<U3')

In [41]:
data

array([[ 0.76168492,  0.88858551, -0.73758065, -0.90576953],
       [ 0.61435373,  0.29488864, -0.825977  ,  1.33579706],
       [-0.16546227, -0.04316199,  0.15786342,  2.81327239],
       [-0.04595294,  0.70619641, -0.01360585, -0.90943483],
       [ 0.07599539,  1.36090189, -0.52718299, -0.29272201],
       [-0.71459233,  0.23522878,  0.77360118, -1.19394116],
       [ 1.95756713, -0.29423782,  1.08784032, -0.53463061]])

In [42]:
names == 'ccc'

array([ True, False, False,  True, False, False,  True])

In [43]:
data[names == 'ccc', :]

array([[ 0.76168492,  0.88858551, -0.73758065, -0.90576953],
       [-0.04595294,  0.70619641, -0.01360585, -0.90943483],
       [ 1.95756713, -0.29423782,  1.08784032, -0.53463061]])